CREATE TABLE IF NOT EXISTS public.sym_search_analytics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  query text NOT NULL CHECK (char_length(query) <= 500),
  intent text NOT NULL CHECK (intent IN ('troubleshooting', 'competitor_intel', 'pricing', 'code_docs', 'compliance')),
  result_count integer NOT NULL DEFAULT 0 CHECK (result_count >= 0),
  latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  cache_hit boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS sym_search_analytics_created_at_idx
  ON public.sym_search_analytics (created_at DESC);

CREATE INDEX IF NOT EXISTS sym_search_analytics_intent_created_at_idx
  ON public.sym_search_analytics (intent, created_at DESC);

ALTER TABLE public.sym_search_analytics ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'sym_search_analytics'
      AND policyname = 'sym_search_analytics_insert_public'
  ) THEN
    CREATE POLICY sym_search_analytics_insert_public
      ON public.sym_search_analytics
      FOR INSERT
      TO anon, authenticated
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'sym_search_analytics'
      AND policyname = 'sym_search_analytics_read_public'
  ) THEN
    CREATE POLICY sym_search_analytics_read_public
      ON public.sym_search_analytics
      FOR SELECT
      TO anon, authenticated
      USING (true);
  END IF;
END $$;

GRANT SELECT, INSERT ON public.sym_search_analytics TO anon, authenticated;
GRANT ALL ON public.sym_search_analytics TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.sym_search_analytics_id_seq TO anon, authenticated, service_role;

COMMENT ON TABLE public.sym_search_analytics IS
  'SymSearch request analytics written by the public research API for latency, cache-hit, and intent tracking.';
